#!/bin/bash

#SBATCH --nodes              1

#SBATCH --ntasks             4
##SBATCH --ntasks-per-node    1
##SBATCH --ntasks-per-socket  1

##SBATCH --cpus-per-task      1

echo
echo "---------------------------------------"
echo


echo "--> ps -O cgroup"
echo
ps -O cgroup
echo
echo "---------------------------------------"
echo


echo "--> env"
echo
env | grep -E 'SLURM_CPUS_ON_NODE|SLURM_JOB_CPUS_PER_NODE|SLURM_NNODES|SLURM_NPROCS|SLURM_NTASKS|SLURM_TASKS_PER_NODE|SLURM_TASK_PID' | sort
echo "---------------------------------------"
echo


echo "--> srun..."
echo
set -x
srun /home/jmenu/pi_test
set +x
echo "---------------------------------------"
echo


echo "--> Processes belonging to ${USER}"
echo
ps auxf | grep ${USER}
# | grep -E 'jmenu|slurmstepd' 
echo

wait

