#!/bin/bash -l

#SBATCH --nodes 1
#SBATCH --ntasks-per-node 4

## cpus-per-task > 1 needed for multithreaded applications
#SBATCH --cpus-per-task 1

## maximum memory needed in MB
#SBATCH --mem 4096

## maximum walltime needed
#SBATCH --time 00:05:00

source /ssoft/spack/bin/slmodules.sh

module purge 
# load the compiler and MPI variant used to generate the executable
module load intel intel-mpi

# compiled with mpiicc hello_mpi.c -o hello_mpi

srun ./hello_mpi

