#!/bin/bash -l 
#SBATCH --job-name Abaqus
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 8
#SBATCH --time 00:10:00
 
source /ssoft/spack/bin/slmodules.sh -r deprecated

module purge
module load intel intelmpi abaqus

# Here is an example with 1 node and 8 cores
# (see the 'Explicit' directory for a multi-node example)
abaqus inter cpus=$SLURM_CPUS_PER_TASK j=umatmst3 user=umatmst3.f
